version: '3'
services:
  reearth-backend:
    build:
      context: .
    image: reearth/reearth-backend:nightly
    environment:
      REEARTH_DB: mongodb://mongo:0X7qz05IOcfon3gjt5JP@containers-us-west-66.railway.app:5651
    ports:
      - '8080:8080'
    # env_file:
    #   - ./.env
    links:
      - reearth-mongo
    depends_on:
      - reearth-mongo
    volumes:
      - ./data:/reearth/data
  reearth-mongo:
    image: mongo:4.4-focal
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
